@W-14955790 BazelEventsExtensionAPI
salesforce/bazel-vscode-java pull request #108
Opened 2024-03-04 21:31 UTC by spuliaiev-sfdc

* Adding BazelEventsExtensionAPI:
  * onSyncStarted event - An event which is fired on start of a Bazel Sync session.
  * onSyncEnded event - An event which is fired on end of a Bazel Sync session.
  * onBazelProjectFileCreated - An event which is fired on creation of a .bazelproject file.
  * onBazelProjectFileUpdated - An event which is fired on updates to the .bazelproject file.
  * onSyncDirectoriesStarted - An event which is fired on start of a Bazel Sync Directories session.
  * onSyncDirectoriesEnded - An event which is fired on end of a Bazel Sync Directories session.
* Adding some logging to track the extension activities, including extension activation

2024-03-05 05:43 UTC, guw requested changes

2024-03-05 05:43 UTC, guw commented on src/apiHandler.ts
> +			onSyncDirectoriesEnded,
That's a lot of APIs. Can it be consolidated into less? I don't see why we need separate calls for start and end. We can submit just the result.

```typescript
    /**
     * Event emitted when a sync operations completed.
     * @param syncMode - mode of synchronization (full, directories)
     * @param status - ok or cancelled or failed
     * @param workspacePath - the Bazel workspace that was synchronized
     * @param durationInMilliseconds - the duration of the synchronization in milliseconds
     */
    public onSyncFinished(syncMode: enum, status: string, workspacePath: string, durationInMilliseconds: number);
```

Also, it's a bit confusing why this is API. Would we expose/export a way to *add* event listeners and these listeners need to implement an interface with that method?

2024-03-05 05:43 UTC, guw commented on src/loggingTCPServer.ts
> +		LOGGER.info('Adjusting vmargs for TCP Server.');
debug not info

2024-03-05 05:44 UTC, guw commented on src/loggingTCPServer.ts
> +			LOGGER.info('Starting TCP Server.');
debug not info?

2024-03-05 05:44 UTC, guw commented on src/loggingTCPServer.ts
> +					LOGGER.info(`Bazel log server listening on port ${port}`);
debug not info?

2024-03-05 05:44 UTC, guw commented on src/loggingTCPServer.ts
> +				BazelLanguageServerTerminal.error('Failed to start bazel TCP server');
Why log twice? I would expect the error be surfaced alrady?

2024-03-05 05:45 UTC, guw commented on src/util.ts
> +		);
What's the value of this creation event? Why would someone interested in this not just register regular file watches?

2024-03-05 05:46 UTC, guw commented on src/extension.ts
> +	LOGGER.info('Extension bazel-vscode-java is being activated');
debug instead of info?

2024-03-05 05:46 UTC, guw commented on src/extension.ts
> +			apiHandler.fireBazelProjectFileUpdated(doc.uri);
What's the value of this creation event? Why would someone interested in this not just register regular file watch?

2024-03-05 05:46 UTC, guw commented on src/extension.ts
> +		LOGGER.info('Bazel Workspace Root detected.');
debug instead of info; also, additional details would be useful (location)

2024-03-05 05:47 UTC, guw commented on src/extension.ts
> +		LOGGER.info('Bazel Workspace Root not detected.');
debug instead of info?

2024-03-05 05:47 UTC, guw commented on src/extension.ts
>  		);
What is the value of duplicate messages?

2024-03-05 05:48 UTC, guw commented on src/extension.ts
> +	apiHandler.fireSyncStarted(workspaceRoot);
What's the value of this creation event? Why not start measuring here?

2024-03-05 05:48 UTC, guw commented on src/extension.ts
> +	);
debug instead of info

2024-03-05 05:49 UTC, guw commented on src/extension.ts
> +					);
that should raise an error, a log message is useless and requires extra support work to investigat/handle/diagnose

2024-03-05 05:49 UTC, guw commented on src/extension.ts
> +			apiHandler.fireSyncDirectoriesEnded(bazelProjectFile.directories);
need to be adapted to api including workspace path, event type, result message and duration

2024-03-05 05:50 UTC, guw commented on src/bazelLangaugeServerTerminal.ts
> +}
That's a brittle contract. We should not be doing this. Instead we should hook into the Java side and emit the event reliably. API already exists

2024-03-05 19:28 UTC, spuliaiev-sfdc commented on src/bazelLangaugeServerTerminal.ts
> +}
If you mean the LanguageClient api - this api client is created in RedHat Java - and not visible for all the other extensions.
Multiple connections to the same LanguageServer is still not supported unfortunately, and the client is not exposed in the redhat extension.
https://github.com/microsoft/language-server-protocol/issues/1359
https://github.com/microsoft/language-server-protocol/issues/1160
https://github.com/microsoft/vscode-languageserver-node/issues/837

2024-03-05 19:29 UTC, spuliaiev-sfdc commented on src/bazelLangaugeServerTerminal.ts
> +}
We can adjust the RedHat java extension, but that would not be easy.

2024-03-05 19:30 UTC, spuliaiev-sfdc commented on src/bazelLangaugeServerTerminal.ts
> +}
@lonhutt suggested to hook on the terminal and catch log messages to identify events.
That's what is done now.
It might be more configurable - to just hold the list of patterns and trigger events basing on matches.
So we can configure them from the interested extensions.

2024-03-05 20:59 UTC, spuliaiev-sfdc commented on src/extension.ts
> +	apiHandler.fireSyncStarted(workspaceRoot);
Because we are not doing telemetry here. Just triggering events.
measuring and creation of spans is done in a separate extensions.

2024-03-05 22:32 UTC, spuliaiev-sfdc commented on src/apiHandler.ts
> +			onSyncDirectoriesEnded,
Added an interface to add event listeners for the BazelTerminalLog - via patterns.
Removed onSyncEnded - because it is based on the log - so it will be configured from telemetry extension

2024-03-05 22:32 UTC, spuliaiev-sfdc commented on src/bazelLangaugeServerTerminal.ts
> +}
Added that configurable patterns into PR

2024-03-05 22:37 UTC, spuliaiev-sfdc commented on src/extension.ts
> +			apiHandler.fireSyncDirectoriesEnded(bazelProjectFile.directories);
There is no duration - it is calculated in a telemetry extension.
No event type - as we do not have onSyncEnded now - so there is no sense to create a typed event.
The only thing left is workspace path - so it's only that provided as parameter.

2024-03-05 22:41 UTC, dkashyn-sfdc commented on src/loggingTCPServer.ts
> +				LOGGER.info('Failed to start bazel TCP server');
do we need port here?

2024-03-06 08:16 UTC, guw commented on src/bazelLangaugeServerTerminal.ts
> +}
@spuliaiev-sfdc I am talking about this extension in the Bazel LS extension: https://github.com/salesforce/bazel-eclipse/blob/main/bundles/com.salesforce.bazel.eclipse.core/src/com/salesforce/bazel/eclipse/core/model/SynchronizationParticipant.java

That's much more stable for telemetry.

2024-03-06 08:18 UTC, guw commented on src/extension.ts
> +			apiHandler.fireSyncDirectoriesEnded(bazelProjectFile.directories);
That's brittle. What if there is a crash or something else and events are received/fired out of order?

This API is not good. We should measure duration here and then submit one single event, similar to how the Bazel LS extension does it.

https://github.com/salesforce/bazel-eclipse/blob/main/bundles/com.salesforce.bazel.eclipse.core/src/com/salesforce/bazel/eclipse/core/events/SyncFinishedEvent.java

2024-04-18 15:40 UTC, closed without merging