updated bazel LS logging approach
salesforce/bazel-vscode-java pull request #48
Opened 2023-09-25 21:38 UTC by lonhutt

2023-09-26 08:55 UTC, guw requested changes

2023-09-26 08:55 UTC, guw commented on src/extension.ts
> +	console.log('finished deleting old project files');
@lonhutt Please remove. This should be done outside by a `mvn clean` or some other way. The project files are important to keep once a workspace is re-opened.

2023-09-26 08:55 UTC, guw commented on src/log.ts
>  export namespace Log {
This should be renamed to reflect the new purpose.

2023-09-26 22:53 UTC, lonhutt commented on src/extension.ts
> +	console.log('finished deleting old project files');
I'll comment it out for now, the idea was to call this after/during a bazelproject file change so we don't keep old project files laying around the filesystem. It seems like the LS is picking up any old .project/.classpath files and loading them, even if they're not in the current project view.

2023-09-26 22:55 UTC, lonhutt commented on src/log.ts
>  export namespace Log {
It's still used for logging out messages from the LS to the console; what do you want to rename it?

2023-09-27 05:02 UTC, guw commented on src/extension.ts
> +	console.log('finished deleting old project files');
The sync projects actions need to be triggered in the LS. Maybe it should be done automatically in the LS. I am not doing it automatically in Eclipse because it's too expensive.

2023-09-27 05:03 UTC, guw commented on src/log.ts
>  export namespace Log {
I think it's no longer a general logging facility but specifically a Bazel Build Status terminal, isn't it? Just to avoid confusion when reading code as an outsider/contributor.

2023-10-02 10:52 UTC, guw commented on src/test/suite/extension.test.ts
> +			assert.ok(connections() > 0);
@lonhutt Can you have a look at the test? It should not be failing.

2023-10-26 19:42 UTC, lonhutt commented on src/bazelRunStatus.ts
> +	bazelStatus.text = `$(sync~spin) bazel building`;
@guw i would love a better phrase here if you can think of one

2023-10-27 14:38 UTC, merged

2023-10-27 14:40 UTC, guw commented on src/bazelRunStatus.ts
> +	bazelStatus.text = `$(sync~spin) bazel building`;
@lonhutt Let's do a follow up commit. I would say `Syncing BUILD files`